debugflag : False

program_mode : Basic # Test Basic

hodomap : True

threshold: 0

lpi: True

fontsize: 14
titlesize: 18

# customize
customize: # east de
  lon1: 10.7
  lon2: 17
  lat1: 50.1
  lat2: 54.8

