levels: [74,20]
steps: 1  # level steps

hodomap : True
soundmap : True

threshold: 0

fontsize: 14
titlesize: 18

# customize
customize: # east de
  lon1: 10.7
  lon2: 17
  lat1: 50.1
  lat2: 54.8

# 10.77, 18.92, 49.80, 55.06
