name: Unittest

on: 
  push:
    branches:
      - 'main'
    paths:
      - '**.js'
  schedule:
    - cron: "0 2 1 * *"


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.10", "3.11", "3.12", "3.13"]


    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run tests with nose2
      continue-on-error: true
      id: unittest
      run: |
        cd test
        nose2