name: Unittest

on:
  push:
    branches: [ "main", "unittest"]
    
jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run tests with nose2
      run: |
        echo "Pythonpath: " $PYTHONPATH
        PYTHONPATH=$GITHUB_WORKSPACE
        echo "Pythonpath: " $PYTHONPATH
        cd test
        nose2
